# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/igeolise/traveltime/rabbitmq/requests/TimeFilterFastResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcom/igeolise/traveltime/rabbitmq/requests/TimeFilterFastResponse.proto\x12*com.igeolise.traveltime.rabbitmq.responses\"\x84\x08\n\x16TimeFilterFastResponse\x12[\n\x05\x65rror\x18\x01 \x01(\x0b\x32H.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorB\x02\x18\x01\x12\x61\n\nproperties\x18\x02 \x01(\x0b\x32M.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.Properties\x1aJ\n\nProperties\x12\x13\n\x0btravelTimes\x18\x01 \x03(\x11\x12\x14\n\x0cmonthlyFares\x18\x02 \x03(\x05\x12\x11\n\tdistances\x18\x03 \x03(\x05\x1a\x63\n\x05\x45rror\x12Z\n\x04type\x18\x01 \x01(\x0e\x32L.com.igeolise.traveltime.rabbitmq.responses.TimeFilterFastResponse.ErrorType\"\xf8\x04\n\tErrorType\x12\x0f\n\x07UNKNOWN\x10\x00\x1a\x02\x08\x01\x12$\n\x1cONE_TO_MANY_MUST_NOT_BE_NULL\x10\x01\x1a\x02\x08\x01\x12\x1f\n\x17SOURCE_MUST_NOT_BE_NULL\x10\x02\x1a\x02\x08\x01\x12\'\n\x1fTRANSPORTATION_MUST_NOT_BE_NULL\x10\x03\x1a\x02\x08\x01\x12\x1e\n\x16SOURCE_NOT_IN_GEOMETRY\x10\x04\x1a\x02\x08\x01\x12(\n UNRECOGNIZED_TRANSPORTATION_MODE\x10\x05\x1a\x02\x08\x01\x12!\n\x19TRAVEL_TIME_LIMIT_TOO_LOW\x10\x06\x1a\x02\x08\x01\x12\"\n\x1aTRAVEL_TIME_LIMIT_TOO_HIGH\x10\x07\x1a\x02\x08\x01\x12\x1d\n\x15\x41UTH_ERROR_NO_USER_ID\x10\x08\x1a\x02\x08\x01\x12\x32\n*SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE\x10\t\x1a\x02\x08\x01\x12\x1b\n\x13SOURCE_OUT_OF_REACH\x10\n\x1a\x02\x08\x01\x12\x33\n+INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS\x10\x0b\x1a\x02\x08\x01\x12\'\n\x1f\x44ISTANCE_PROPERTY_NOT_SUPPORTED\x10\x0c\x1a\x02\x08\x01\x12\x37\n/BOTH_MANY_TO_ONE_AND_ONE_TO_MANY_CANNOT_BE_SENT\x10\r\x1a\x02\x08\x01\x12\x33\n+ONE_TO_MANY_OR_MANY_TO_ONE_MUST_NOT_BE_NULL\x10\x0e\x1a\x02\x08\x01\x12\x1d\n\x15INVALID_PROTO_REQUEST\x10\x0f\x1a\x02\x08\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["UNKNOWN"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["UNKNOWN"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["ONE_TO_MANY_MUST_NOT_BE_NULL"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["ONE_TO_MANY_MUST_NOT_BE_NULL"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_MUST_NOT_BE_NULL"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_MUST_NOT_BE_NULL"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRANSPORTATION_MUST_NOT_BE_NULL"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRANSPORTATION_MUST_NOT_BE_NULL"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_NOT_IN_GEOMETRY"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_NOT_IN_GEOMETRY"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["UNRECOGNIZED_TRANSPORTATION_MODE"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["UNRECOGNIZED_TRANSPORTATION_MODE"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRAVEL_TIME_LIMIT_TOO_LOW"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRAVEL_TIME_LIMIT_TOO_LOW"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRAVEL_TIME_LIMIT_TOO_HIGH"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["TRAVEL_TIME_LIMIT_TOO_HIGH"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["AUTH_ERROR_NO_USER_ID"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["AUTH_ERROR_NO_USER_ID"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SERVICE_MISMATCH_WRONG_TRANSPORTATION_MODE"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_OUT_OF_REACH"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["SOURCE_OUT_OF_REACH"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["INTERLEAVED_DELTAS_INVALID_COORDINATE_PAIRS"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["DISTANCE_PROPERTY_NOT_SUPPORTED"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["DISTANCE_PROPERTY_NOT_SUPPORTED"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["BOTH_MANY_TO_ONE_AND_ONE_TO_MANY_CANNOT_BE_SENT"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["BOTH_MANY_TO_ONE_AND_ONE_TO_MANY_CANNOT_BE_SENT"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["ONE_TO_MANY_OR_MANY_TO_ONE_MUST_NOT_BE_NULL"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["ONE_TO_MANY_OR_MANY_TO_ONE_MUST_NOT_BE_NULL"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["INVALID_PROTO_REQUEST"]._options = None
  _TIMEFILTERFASTRESPONSE_ERRORTYPE.values_by_name["INVALID_PROTO_REQUEST"]._serialized_options = b'\010\001'
  _TIMEFILTERFASTRESPONSE.fields_by_name['error']._options = None
  _TIMEFILTERFASTRESPONSE.fields_by_name['error']._serialized_options = b'\030\001'
  _TIMEFILTERFASTRESPONSE._serialized_start=119
  _TIMEFILTERFASTRESPONSE._serialized_end=1147
  _TIMEFILTERFASTRESPONSE_PROPERTIES._serialized_start=337
  _TIMEFILTERFASTRESPONSE_PROPERTIES._serialized_end=411
  _TIMEFILTERFASTRESPONSE_ERROR._serialized_start=413
  _TIMEFILTERFASTRESPONSE_ERROR._serialized_end=512
  _TIMEFILTERFASTRESPONSE_ERRORTYPE._serialized_start=515
  _TIMEFILTERFASTRESPONSE_ERRORTYPE._serialized_end=1147
# @@protoc_insertion_point(module_scope)
