# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/igeolise/traveltime/rabbitmq/requests/TimeFilterFastRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.igeolise.traveltime.rabbitmq.requests import RequestsCommon_pb2 as com_dot_igeolise_dot_traveltime_dot_rabbitmq_dot_requests_dot_RequestsCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcom/igeolise/traveltime/rabbitmq/requests/TimeFilterFastRequest.proto\x12)com.igeolise.traveltime.rabbitmq.requests\x1a>com/igeolise/traveltime/rabbitmq/requests/RequestsCommon.proto\"\x9f\x08\n\x15TimeFilterFastRequest\x12\x64\n\x10oneToManyRequest\x18\x01 \x01(\x0b\x32J.com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.OneToMany\x12\x64\n\x10manyToOneRequest\x18\x02 \x01(\x0b\x32J.com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.ManyToOne\x1a\x89\x03\n\tOneToMany\x12L\n\x11\x64\x65partureLocation\x18\x01 \x01(\x0b\x32\x31.com.igeolise.traveltime.rabbitmq.requests.Coords\x12\x16\n\x0elocationDeltas\x18\x02 \x03(\x11\x12Q\n\x0etransportation\x18\x03 \x01(\x0b\x32\x39.com.igeolise.traveltime.rabbitmq.requests.Transportation\x12P\n\x11\x61rrivalTimePeriod\x18\x04 \x01(\x0e\x32\x35.com.igeolise.traveltime.rabbitmq.requests.TimePeriod\x12\x12\n\ntravelTime\x18\x05 \x01(\x11\x12]\n\nproperties\x18\x06 \x03(\x0e\x32I.com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.Property\x1a\x87\x03\n\tManyToOne\x12J\n\x0f\x61rrivalLocation\x18\x01 \x01(\x0b\x32\x31.com.igeolise.traveltime.rabbitmq.requests.Coords\x12\x16\n\x0elocationDeltas\x18\x02 \x03(\x11\x12Q\n\x0etransportation\x18\x03 \x01(\x0b\x32\x39.com.igeolise.traveltime.rabbitmq.requests.Transportation\x12P\n\x11\x61rrivalTimePeriod\x18\x04 \x01(\x0e\x32\x35.com.igeolise.traveltime.rabbitmq.requests.TimePeriod\x12\x12\n\ntravelTime\x18\x05 \x01(\x11\x12]\n\nproperties\x18\x06 \x03(\x0e\x32I.com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest.Property\"$\n\x08Property\x12\t\n\x05\x46\x41RES\x10\x00\x12\r\n\tDISTANCES\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.igeolise.traveltime.rabbitmq.requests.TimeFilterFastRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEFILTERFASTREQUEST._serialized_start=181
  _TIMEFILTERFASTREQUEST._serialized_end=1236
  _TIMEFILTERFASTREQUEST_ONETOMANY._serialized_start=411
  _TIMEFILTERFASTREQUEST_ONETOMANY._serialized_end=804
  _TIMEFILTERFASTREQUEST_MANYTOONE._serialized_start=807
  _TIMEFILTERFASTREQUEST_MANYTOONE._serialized_end=1198
  _TIMEFILTERFASTREQUEST_PROPERTY._serialized_start=1200
  _TIMEFILTERFASTREQUEST_PROPERTY._serialized_end=1236
# @@protoc_insertion_point(module_scope)
